DELETE http://localhost:4000/api/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzE3ODc0Njg3LCJ1c2VySWQiOjJ9.JM0MWZkjabueB9WsDSWeFJHHQIFJuYsEGyfF3-sHQWU