PUT http://localhost:4000/api/events/2
Content-Type: application/json

{
  "name": "Updated event",
  "description": "Just an updated event!!!",
  "location": "Lahore, Pakistan",
  "dateTime": "2025-10-20T08:25:00.000Z"
}